### ISSUE TITLE
Plans to make this an unmanaged package?

### ISSUE THREAD

**Issue by omniphx** [ChuckJonas/APEX-Q#2]
This is a really cool library! Would love a way to easily install/update it.

**Comment by ChuckJonas** [comment]
@omniphx thanks,

## Updated

So this currently includes an [build script](https://github.com/kevinohara80/sfdc-pkg-postinstall) that makes it very easy to bring into your existing project.  

if you run `npm install apex-q` from your root of a salesforce project, it will install files into your `src` directory (note: it will also create a `node_models` folder.  You can then deploy it with Mavensmate, DMC, Eclipse or whatever your IDE of choice is. 

This is kinda an experiment idea but has some advantages over Unmanaged Packages.

If that doesn't work for you, you're more than welcome to fork this and package it!

**Comment by omniphx** [comment]
So running `npm install apex-q` doesn't merge the contents into my src directory (using Mavensmate btw). Here's the output:

```
> apex-q@1.0.0 postinstall C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q
> node -e "require('sfdc-pkg-postinstall').install()"


SFDC PACKAGE POST INSTALL => apex-q@1.0.0
  -> package src dir: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src
  -> project src dir: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q\src
  -> merging files

  -> merging dir: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src
  -> merging dir: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/Q.cls
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/Q.cls-meta.xml
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/QBase.cls
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/QBase.cls-meta.xml
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/QFuture.cls
  -> merging file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/classes/QFuture.cls-meta.xml
  -> ignoring file: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q/src/package.xml

  -> merge complete!

apex-q@1.0.0 node_modules\apex-q
└── sfdc-pkg-postinstall@1.0.0
```

Seems like this package is missing a way to configure the src directory. Also was under the impression that the package could handle the deployment aspect as well (but that doesn't currently seem to be the case)

I'll close this ticket and move this issue to the other repository. I do really like how you are adopting npm. Its seems like a much simpler solution to handle Salesforce package management.

**Comment by ChuckJonas** [comment]
I just ran it at the root of my projects and here is the output:

```
SFDC PACKAGE POST INSTALL => apex-q@1.0.0
  -> package src dir: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src
  -> project src dir: /Users/jonas/Documents/mm/ccc-sfdc/src
  -> merging files

  -> merging dir: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src
  -> merging dir: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/Q.cls
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/Q.cls-meta.xml
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/QBase.cls
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/QBase.cls-meta.xml
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/QFuture.cls
  -> merging file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/classes/QFuture.cls-meta.xml
  -> ignoring file: /Users/jonas/Documents/mm/ccc-sfdc/node_modules/apex-q/src/package.xml

  -> merge complete!
```

The second post install line seems to be where yours is going wrong:
`-> project src dir: /Users/jonas/Documents/mm/ccc-sfdc/src` vs
`project src dir: C:\Users\matthew.mitchener\Salesforce\Marty2\node_modules\apex-q\src`

did you run it from the root of your workspace (folder containing `src`)?

When I first added it, I was also under the impression that `sfdc-pkg-postinstall` would push meta-data to the org.  However, on second thought, its probably better that it doesn't (just incase it overwrites a conflicting file).

**Comment by omniphx** [comment]
Ah.. guess I was in the root of my Mavensmate project, not the src folder.

Getting a little off topic, but I think it would actually be nice to deploy the files. Would want to configure the destination deployment and if conflicts arise the user could be prompted to overwrite/rename.

**Comment by ChuckJonas** [comment]
sorry that was ambiguous.  You should actually be running it from the workspace root.  

`> cd .` should output `/src/classes/..`
